config/routes.rb
Rails.application.routes.draw do
  resources :books do
    resources :reviews
  end

  root 'books#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
  validates :title, presence: true
  validates :author, presence: true
  validates :year, presence: true
  validates :description, presence: true
  validates :category, presence: true

  has_many :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
  validates :body, presence: true
  validates :rating, presence: true, inclusion: { in: 1..5 }

  belongs_to :book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to @book
    else
      render "new"
    end
  end

  def show
    @book = Book.find(params[:id])
    @review = Review.new
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :year,
                                 :description, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @book = Book.find(params[:book_id])
    @review.book_id = params[:book_id]
    if @review.save
      redirect_to @book
    else
      render "books/show"
    end
  end

  private

  def review_params
    params.require(:review).permit(:body, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/index.html.erb
<div class="row information">

  <h1>List of All Books</h1>

  <ul>
    <% @books.each do |book| %>
      <li><%= link_to book.title, book_path(book.id) %><br>
          <%= "#{book.author}, #{book.year}" %><br>
          <%= "#{book.category}" %></li>
    <% end %>
  </ul>

  <%= link_to "Add a Book", new_book_path, class: "button" %>
</div>

app/views/books/new.html.erb
<div class="row information">

  <h1>Add a New Book</h1>

    <%= form_for @book do |f| %>

    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>

    <p>
      <%= f.label :author %><br>
      <%= f.text_field :author %>
    </p>
    <p>
      <%= f.label :year %><br>
      <%= f.text_field :year %>
    </p>

    <p>
      <%= f.label :description %><br>
      <%= f.text_field :description %>
    </p>

    <p>
      <%= f.label :category %><br>
      <%= f.text_field :category %>
    </p>

      <%= f.submit "Add Book", class: "button" %>

    <% end %>

</div>

app/views/books/show.html.erb
<div class="row information">

  <h1><%= @book.title %></h1>
  <h3><%= "Written by: #{@book.author}, #{@book.year}" %></h3>
  <h4><%= @book.category %></h4>
  <hr>

  <p>
    <%= @book.description %>
  </p>

  <a style="center"><%= link_to "Home", root_path, class: "button tiny" %></a><br>
  <hr>

  <h2><%= "#{@book.title}'s Reviews" %></h2>
  <ul>
    <% @book.reviews.each do |review| %>
      <li><%= "#{review.body}" %> - <%= "#{review.rating}" %><br>
          <%= "#{review.updated_at}" %></li>
    <% end %>
  </ul>
  <br>

  <h3>Write a Review</h3>

    <%= form_for [@book, @review] do |f| %>

    <p>
      <%= f.label :body %><br>
      <%= f.text_field :body %>
    </p>

    <p>
      <%= f.label :rating  %><br>
      <%= f.select :rating, 1..5 %>
    </p>

    <%= f.submit "Submit Review", class: "button" %>

    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>